# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('liveedu_project', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='anonymous_ip',
            field=models.GenericIPAddressField(null=True, protocol='IPv4'),
        ),
    ]
