# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('liveedu_project', '0004_auto_20180610_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='anonymous_ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
    ]
