# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('liveedu_project', '0005_auto_20180610_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_rel', to='liveedu_project.Project'),
        ),
    ]
